spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qrcode?useSSL=false&useUnicode=true&characterEncode=true&charaterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: LJY123456
    initialSize:20
    minIdle:50
    maxActive:500
  jpa:
    hibernate:
      ddl-auto:update
    show-sql:true
